# base_conocimiento.py
# Contiene la base de preguntas del sistema experto.

base_de_conocimiento = {
    # DIMENSIÓN: FÍSICA Y PSICOLÓGICA (1-21)
    "1": {"pregunta": "¿Tienes moretones o marcas que no puedes explicar después de convivir con esa persona?",
          "hipotesis": [("violencia_fisica", 0.92), ("violencia_psicologica", 0.22)]},
    "2": {"pregunta": "¿Te han empujado durante una discusión o al intentar retirarte?",
          "hipotesis": [("violencia_fisica", 0.60), ("violencia_psicologica", 0.30)]},
    "3": {"pregunta": "¿Has recibido jalones, bofetadas o golpes durante un conflicto?",
          "hipotesis": [("violencia_fisica", 0.80), ("violencia_psicologica", 0.40)]},
    "4": {"pregunta": "¿Te han sujetado con fuerza para impedir que te muevas o te alejes?",
          "hipotesis": [("violencia_fisica", 0.70), ("violencia_psicologica", 0.35)]},
    "5": {"pregunta": "¿Te impiden salir de un lugar cuando quieres irte?",
          "hipotesis": [("violencia_psicologica", 0.60), ("violencia_fisica", 0.30)]},
    "6": {"pregunta": "¿Te han aventado o empujado contra una pared o un mueble?",
          "hipotesis": [("violencia_fisica", 0.85), ("violencia_psicologica", 0.40)]},
    "7": {"pregunta": "¿Te han jalado del cabello o de la ropa para detenerte?",
          "hipotesis": [("violencia_fisica", 0.75), ("violencia_psicologica", 0.30)]},
    "8": {"pregunta": "¿Te han aventado objetos cerca o hacia ti para intimidarte?",
          "hipotesis": [("violencia_fisica", 0.50), ("violencia_psicologica", 0.60)]},
    "9": {"pregunta": "¿Presentas marcas de dedos, sujetones o agarres en brazos o muñecas?",
          "hipotesis": [("violencia_fisica", 0.85), ("violencia_psicologica", 0.40)]},
    "10": {"pregunta": "¿Sientes dolor físico después de una discusión o enfrentamiento?",
           "hipotesis": [("violencia_fisica", 0.70), ("violencia_psicologica", 0.50)]},
    "11": {"pregunta": "¿Te has lesionado varias veces en contextos parecidos sin una explicación convincente?",
           "hipotesis": [("violencia_fisica", 0.80), ("violencia_psicologica", 0.40)]},
    "12": {"pregunta": "¿Alguien te ha inmovilizado o impedido moverte durante un conflicto?",
           "hipotesis": [("violencia_fisica", 0.75), ("violencia_psicologica", 0.45)]},
    "13": {"pregunta": "¿Golpean paredes, puertas u objetos cerca de ti para asustarte?",
           "hipotesis": [("violencia_fisica", 0.40), ("violencia_psicologica", 0.70)]},
    "14": {"pregunta": "¿Te cierran el paso o te rodean para presionarte físicamente?",
           "hipotesis": [("violencia_fisica", 0.50), ("violencia_psicologica", 0.65)]},
    "15": {"pregunta": "¿Te empujan o apartan cuando intentas hablar o defenderte?",
           "hipotesis": [("violencia_fisica", 0.60), ("violencia_psicologica", 0.40)]},
    "16": {"pregunta": "¿Te queda dolor en muñecas, brazos o cuello por cómo te sujetaron?",
           "hipotesis": [("violencia_fisica", 0.85), ("violencia_psicologica", 0.30)]},
    "17": {"pregunta": "¿Te han tirado al suelo durante una pelea o discusión?",
           "hipotesis": [("violencia_fisica", 0.80), ("violencia_psicologica", 0.40)]},
    "18": {"pregunta": "¿Usan objetos de casa para amenazarte o golpearte?",
           "hipotesis": [("violencia_fisica", 0.85), ("violencia_psicologica", 0.60)]},
    "19": {"pregunta": "¿Te impiden buscar atención médica después de una agresión?",
           "hipotesis": [("violencia_fisica", 0.60), ("violencia_psicologica", 0.70), ("negligencia", 0.50)]},
    "20": {"pregunta": "¿Te han sacudido o zamarreado durante una discusión?",
           "hipotesis": [("violencia_fisica", 0.65), ("violencia_psicologica", 0.35)]},
    "21": {"pregunta": "¿Notas dolor o molestia corporal frecuente después de convivir con esa persona?",
           "hipotesis": [("violencia_fisica", 0.50), ("violencia_psicologica", 0.40)]},

    # DIMENSIÓN: PSICOLÓGICA (22-42)
    "22": {"pregunta": "¿Te hacen sentir responsable de casi todo lo malo que ocurre?",
           "hipotesis": [("violencia_psicologica", 0.80)]},
    "23": {"pregunta": "¿Te ponen obstáculos para convivir con tus amistades o familia?",
           "hipotesis": [("violencia_psicologica", 0.75)]},
    "24": {"pregunta": "¿Sientes que te vigilan o controlan casi todo el tiempo?",
           "hipotesis": [("violencia_psicologica", 0.85)]},
    "25": {"pregunta": "¿Minimizan o invalidan lo que sientes cuando expresas una molestia?",
           "hipotesis": [("violencia_psicologica", 0.70)]},
    "26": {"pregunta": "¿Te amenazan con dejarte solo, sacarte de la casa o retirarte apoyo?",
           "hipotesis": [("violencia_psicologica", 0.80), ("violencia_economica", 0.30)]},
    "27": {"pregunta": "¿Cambian la versión de los hechos para confundirte o hacerte dudar?",
           "hipotesis": [("violencia_psicologica", 0.90)]},  # Gaslighting
    "28": {"pregunta": "¿Usan el silencio prolongado como castigo cuando haces algo que no les gusta?",
           "hipotesis": [("violencia_psicologica", 0.75)]},
    "29": {"pregunta": "¿Te humillan o ridiculizan cuando están solos contigo?",
           "hipotesis": [("violencia_psicologica", 0.80), ("violencia_verbal", 0.50)]},
    "30": {"pregunta": "¿Te dicen que recuerdas mal aunque estés seguro de lo ocurrido?",
           "hipotesis": [("violencia_psicologica", 0.85)]},
    "31": {"pregunta": "¿Usan los celos para controlar con quién hablas o dónde vas?",
           "hipotesis": [("violencia_psicologica", 0.80)]},
    "32": {"pregunta": "¿Sientes que debes pedir permiso para acciones básicas de tu vida?",
           "hipotesis": [("violencia_psicologica", 0.70)]},
    "33": {"pregunta": "¿Te dicen que tú provocas su enojo o su maltrato?",
           "hipotesis": [("violencia_psicologica", 0.85)]},
    "34": {"pregunta": "¿Te sientes inseguro o en alerta dentro de tu casa o espacio cercano?",
           "hipotesis": [("violencia_psicologica", 0.75)]},
    "35": {"pregunta": "¿Te comparan con otras personas para hacerte sentir menos?",
           "hipotesis": [("violencia_psicologica", 0.70), ("violencia_verbal", 0.40)]},
    "36": {"pregunta": "¿Te amenazan con divulgar información personal para presionarte?",
           "hipotesis": [("violencia_psicologica", 0.80), ("violencia_digital", 0.40)]},
    "37": {"pregunta": "¿Te quitan libertad para decidir sobre estudios, trabajo o actividades?",
           "hipotesis": [("violencia_psicologica", 0.75), ("violencia_economica", 0.40)]},
    "38": {"pregunta": "¿Te dicen que nadie te va a creer si cuentas lo que pasa?",
           "hipotesis": [("violencia_psicologica", 0.85)]},
    "39": {"pregunta": "¿Observan cada reacción tuya para corregirte o intimidarte?",
           "hipotesis": [("violencia_psicologica", 0.70)]},
    "40": {"pregunta": "¿Sientes que te dejan sin apoyo emocional de forma intencional?",
           "hipotesis": [("violencia_psicologica", 0.65)]},
    "41": {"pregunta": "¿Te dicen que exageras o inventas cuando cuentas un problema?",
           "hipotesis": [("violencia_psicologica", 0.75)]},
    "42": {"pregunta": "¿Usan el miedo o la presión para que obedezcas sin cuestionar?",
           "hipotesis": [("violencia_psicologica", 0.85)]},

    # DIMENSIÓN: VERBAL (43-63)
    "43": {"pregunta": "¿Te insultan de manera directa cuando se enojan contigo?",
           "hipotesis": [("violencia_verbal", 0.85), ("violencia_psicologica", 0.50)]},
    "44": {"pregunta": "¿Te hablan a gritos de forma repetida o para intimidarte?",
           "hipotesis": [("violencia_verbal", 0.80), ("violencia_psicologica", 0.60)]},
    "45": {"pregunta": "¿Te ponen apodos ofensivos o degradantes?",
           "hipotesis": [("violencia_verbal", 0.85), ("violencia_psicologica", 0.40)]},
    "46": {"pregunta": "¿Se burlan de tus errores para hacerte sentir mal?",
           "hipotesis": [("violencia_verbal", 0.70), ("violencia_psicologica", 0.60)]},
    "47": {"pregunta": "¿Te descalifican o te hablan como si no valieras?",
           "hipotesis": [("violencia_verbal", 0.80), ("violencia_psicologica", 0.70)]},
    "48": {"pregunta": "¿Te humillan delante de otras personas?",
           "hipotesis": [("violencia_verbal", 0.75), ("violencia_psicologica", 0.85)]},
    "49": {"pregunta": "¿Te amenazan con hacerte daño, echarte o castigarte?",
           "hipotesis": [("violencia_verbal", 0.85), ("violencia_psicologica", 0.80)]},
    "50": {"pregunta": "¿Usan palabras degradantes para referirse a ti?",
           "hipotesis": [("violencia_verbal", 0.90), ("violencia_psicologica", 0.60)]},
    "51": {"pregunta": "¿Usan sarcasmo o burlas que te dejan en ridículo?",
           "hipotesis": [("violencia_verbal", 0.70), ("violencia_psicologica", 0.65)]},
    "52": {"pregunta": "¿Te interrumpen o no te dejan terminar de hablar?",
           "hipotesis": [("violencia_verbal", 0.60), ("violencia_psicologica", 0.40)]},
    "53": {"pregunta": "¿Te corrigen de manera humillante o con desprecio?",
           "hipotesis": [("violencia_verbal", 0.80), ("violencia_psicologica", 0.70)]},
    "54": {"pregunta": "¿Se burlan de ti cuando expresas tristeza, enojo o miedo?",
           "hipotesis": [("violencia_verbal", 0.75), ("violencia_psicologica", 0.80)]},
    "55": {"pregunta": "¿Te dicen cosas como que no sirves, no puedes o no vales?",
           "hipotesis": [("violencia_verbal", 0.85), ("violencia_psicologica", 0.85)]},
    "56": {"pregunta": "¿Te gritan delante de familiares o personas cercanas?",
           "hipotesis": [("violencia_verbal", 0.80), ("violencia_psicologica", 0.70)]},
    "57": {"pregunta": "¿Desacreditan tu opinión o tus logros de manera repetida?",
           "hipotesis": [("violencia_verbal", 0.75), ("violencia_psicologica", 0.75)]},
    "58": {"pregunta": "¿Te mandan mensajes ofensivos o insultantes?",
           "hipotesis": [("violencia_verbal", 0.80), ("violencia_digital", 0.70)]},
    "59": {"pregunta": "¿Te callan con palabras agresivas cuando intentas hablar?",
           "hipotesis": [("violencia_verbal", 0.85), ("violencia_psicologica", 0.50)]},
    "60": {"pregunta": "¿Se burlan de ti cuando lloras o muestras vulnerabilidad?",
           "hipotesis": [("violencia_verbal", 0.75), ("violencia_psicologica", 0.80)]},
    "61": {"pregunta": "¿Te culpan usando insultos o palabras ofensivas?",
           "hipotesis": [("violencia_verbal", 0.90), ("violencia_psicologica", 0.60)]},
    "62": {"pregunta": "¿Te dicen que te van a echar o dejar fuera usando gritos o insultos?",
           "hipotesis": [("violencia_verbal", 0.85), ("violencia_economica", 0.40)]},
    "63": {"pregunta": "¿Te hacen comentarios ofensivos sobre tu vida, decisiones o forma de ser?",
           "hipotesis": [("violencia_verbal", 0.80), ("violencia_psicologica", 0.60)]},

    # DIMENSIÓN: ECONÓMICA / PATRIMONIAL (64-84)
    "64": {"pregunta": "¿Controlan o retienen el dinero que ganas?", "hipotesis": [("violencia_economica", 0.90)]},
    "65": {"pregunta": "¿Te quitan la tarjeta, clave o acceso a tu dinero?",
           "hipotesis": [("violencia_economica", 0.95)]},
    "66": {"pregunta": "¿Te exigen justificar cada gasto que haces?",
           "hipotesis": [("violencia_economica", 0.75), ("violencia_psicologica", 0.40)]},
    "67": {"pregunta": "¿Te ponen obstáculos para que trabajes o busques empleo?",
           "hipotesis": [("violencia_economica", 0.85), ("violencia_psicologica", 0.50)]},
    "68": {"pregunta": "¿Te obligan a pedir dinero para cosas básicas?", "hipotesis": [("violencia_economica", 0.80)]},
    "69": {"pregunta": "¿Ocultan o restringen dinero para castigarte o controlarte?",
           "hipotesis": [("violencia_economica", 0.90), ("violencia_psicologica", 0.60)]},
    "70": {"pregunta": "¿Usan tu nombre o te meten en deudas sin tu autorización?",
           "hipotesis": [("violencia_economica", 0.95)]},
    "71": {"pregunta": "¿Hacen compras o contratos con tu nombre sin consultarte?",
           "hipotesis": [("violencia_economica", 0.90)]},
    "72": {"pregunta": "¿Te quitan documentos importantes para limitarte?",
           "hipotesis": [("violencia_economica", 0.80), ("violencia_psicologica", 0.60)]},
    "73": {"pregunta": "¿Te impiden pagar o usar transporte para tus actividades?",
           "hipotesis": [("violencia_economica", 0.85), ("violencia_fisica", 0.30)]},
    "74": {"pregunta": "¿Te niegan dinero para comida, medicinas o necesidades básicas?",
           "hipotesis": [("violencia_economica", 0.95), ("negligencia", 0.60)]},
    "75": {"pregunta": "¿Te exigen entregar todo tu ingreso o beca?", "hipotesis": [("violencia_economica", 0.90)]},
    "76": {"pregunta": "¿Retrasan a propósito el dinero que te corresponde para controlarte?",
           "hipotesis": [("violencia_economica", 0.80)]},
    "77": {"pregunta": "¿Usan el dinero para impedir que sigas estudiando o capacitándote?",
           "hipotesis": [("violencia_economica", 0.85)]},
    "78": {"pregunta": "¿Te hacen cubrir gastos que no te corresponden?", "hipotesis": [("violencia_economica", 0.70)]},
    "79": {"pregunta": "¿Te condicionan comida, apoyo o recursos a obedecer?",
           "hipotesis": [("violencia_economica", 0.90), ("violencia_psicologica", 0.70)]},
    "80": {"pregunta": "¿Retienen beca, pensión o ayuda económica que te corresponde?",
           "hipotesis": [("violencia_economica", 0.95)]},
    "81": {"pregunta": "¿Te revisan y cuestionan constantemente cada compra?",
           "hipotesis": [("violencia_economica", 0.75), ("violencia_psicologica", 0.50)]},
    "82": {"pregunta": "¿Cortan internet, luz, comida u otros servicios para presionarte?",
           "hipotesis": [("violencia_economica", 0.85), ("violencia_psicologica", 0.60)]},
    "83": {"pregunta": "¿Te presionan para que renuncies o dejes tu empleo?",
           "hipotesis": [("violencia_economica", 0.80), ("violencia_psicologica", 0.50)]},
    "84": {"pregunta": "¿Sientes que te mantienen sin recursos para que dependas de ellos?",
           "hipotesis": [("violencia_economica", 0.90), ("violencia_psicologica", 0.60)]},

    # DIMENSIÓN: SEXUAL (85-105)
    "85": {"pregunta": "¿Te tocan partes íntimas sin tu consentimiento?", "hipotesis": [("violencia_sexual", 0.95)]},
    "86": {"pregunta": "¿Te presionan para besos, abrazos o contacto físico que no quieres?",
           "hipotesis": [("violencia_sexual", 0.85), ("violencia_psicologica", 0.40)]},
    "87": {"pregunta": "¿Insisten en conductas sexuales después de que dijiste que no?",
           "hipotesis": [("violencia_sexual", 0.90)]},
    "88": {"pregunta": "¿Te hacen comentarios sexuales que te incomodan o te avergüenzan?",
           "hipotesis": [("violencia_sexual", 0.75), ("violencia_verbal", 0.60)]},
    "89": {"pregunta": "¿Te presionan para enviar imágenes íntimas o privadas?",
           "hipotesis": [("violencia_sexual", 0.85), ("violencia_digital", 0.70)]},
    "90": {"pregunta": "¿Comparten fotos o videos íntimos sin tu autorización?",
           "hipotesis": [("violencia_sexual", 0.95), ("violencia_digital", 0.90)]},
    "91": {"pregunta": "¿Te tocan de forma invasiva aunque hayas pedido que paren?",
           "hipotesis": [("violencia_sexual", 0.95)]},
    "92": {"pregunta": "¿Te obligan a ver contenido sexual o situaciones que no deseas?",
           "hipotesis": [("violencia_sexual", 0.85)]},
    "93": {"pregunta": "¿Te amenazan o presionan para conseguir favores de tipo sexual?",
           "hipotesis": [("violencia_sexual", 0.90), ("violencia_psicologica", 0.60)]},
    "94": {"pregunta": "¿Ignoran tus límites físicos incluso cuando los expresas claramente?",
           "hipotesis": [("violencia_sexual", 0.80), ("violencia_fisica", 0.40)]},
    "95": {"pregunta": "¿Reaccionan con enojo o castigo cuando rechazas algo sexual?",
           "hipotesis": [("violencia_sexual", 0.85), ("violencia_psicologica", 0.70)]},
    "96": {"pregunta": "¿Te hacen preguntas sexuales que te incomodan o invaden tu privacidad?",
           "hipotesis": [("violencia_sexual", 0.65), ("violencia_verbal", 0.50)]},
    "97": {"pregunta": "¿Te manipulan para aceptar contacto físico o sexual?",
           "hipotesis": [("violencia_sexual", 0.80), ("violencia_psicologica", 0.75)]},
    "98": {"pregunta": "¿Te hacen quedarte en una situación íntima o incómoda aunque quieras salir?",
           "hipotesis": [("violencia_sexual", 0.85), ("violencia_fisica", 0.50)]},
    "99": {"pregunta": "¿Revisan tu cuerpo o tu ropa sin que tú lo autorices?",
           "hipotesis": [("violencia_sexual", 0.75), ("violencia_fisica", 0.40)]},
    "100": {"pregunta": "¿Hacen chistes sexuales repetidos que te incomodan?",
            "hipotesis": [("violencia_sexual", 0.60), ("violencia_verbal", 0.60)]},
    "101": {"pregunta": "¿Toman fotos o videos de ti sin pedir autorización?",
            "hipotesis": [("violencia_sexual", 0.75), ("violencia_digital", 0.60)]},
    "102": {"pregunta": "¿Usan regalos, dinero o favores para presionarte sexualmente?",
            "hipotesis": [("violencia_sexual", 0.85), ("violencia_economica", 0.60)]},
    "103": {"pregunta": "¿Te dejan de hablar, te castigan o te presionan cuando marcas límites?",
            "hipotesis": [("violencia_sexual", 0.70), ("violencia_psicologica", 0.80)]},
    "104": {"pregunta": "¿Te han tocado de forma íntima cuando estabas dormido/a o descansando?",
            "hipotesis": [("violencia_sexual", 0.95)]},
    "105": {"pregunta": "¿Usan comentarios sobre tu cuerpo para presionarte o incomodarte?",
            "hipotesis": [("violencia_sexual", 0.75), ("violencia_verbal", 0.60)]},

    # DIMENSIÓN: DIGITAL (106-126)
    "106": {"pregunta": "¿Te piden contraseñas o códigos de acceso para revisar tus cuentas?",
            "hipotesis": [("violencia_digital", 0.85), ("violencia_psicologica", 0.50)]},
    "107": {"pregunta": "¿Revisan tu celular, chats o fotos sin tu permiso?",
            "hipotesis": [("violencia_digital", 0.90), ("violencia_psicologica", 0.60)]},
    "108": {"pregunta": "¿Exigen saber dónde estás en tiempo real o revisan tu ubicación constantemente?",
            "hipotesis": [("violencia_digital", 0.85), ("violencia_psicologica", 0.75)]},
    "109": {"pregunta": "¿Te exigen responder mensajes o llamadas de inmediato siempre?",
            "hipotesis": [("violencia_digital", 0.75), ("violencia_psicologica", 0.80)]},
    "110": {"pregunta": "¿Crean cuentas falsas para vigilarte, seguirte o provocarte?",
            "hipotesis": [("violencia_digital", 0.90)]},
    "111": {"pregunta": "¿Publican información, fotos o estados tuyos sin pedirte permiso?",
            "hipotesis": [("violencia_digital", 0.85)]},
    "112": {"pregunta": "¿Comparten fotos o conversaciones privadas sin autorización?",
            "hipotesis": [("violencia_digital", 0.95), ("violencia_psicologica", 0.70)]},
    "113": {"pregunta": "¿Te mandan mensajes ofensivos, burlones o amenazantes?",
            "hipotesis": [("violencia_digital", 0.80), ("violencia_verbal", 0.80)]},
    "114": {"pregunta": "¿Te amenazan, hostigan o exhiben en redes sociales?",
            "hipotesis": [("violencia_digital", 0.95), ("violencia_psicologica", 0.85)]},
    "115": {"pregunta": "¿Te obligan a enseñar chats, llamadas o redes para comprobar algo?",
            "hipotesis": [("violencia_digital", 0.85), ("violencia_psicologica", 0.70)]},
    "116": {"pregunta": "¿Te cambian claves o te bloquean el acceso a cuentas sin avisarte?",
            "hipotesis": [("violencia_digital", 0.90)]},
    "117": {"pregunta": "¿Usan aplicaciones o herramientas para rastrear tu movimiento?",
            "hipotesis": [("violencia_digital", 0.95), ("violencia_psicologica", 0.85)]},
    "118": {"pregunta": "¿Te llaman por video para comprobar dónde estás o con quién estás?",
            "hipotesis": [("violencia_digital", 0.80), ("violencia_psicologica", 0.75)]},
    "119": {"pregunta": "¿Revisan con quién interactúas en redes para controlarte?",
            "hipotesis": [("violencia_digital", 0.85)]},
    "120": {"pregunta": "¿Sientes que no tienes privacidad en tu vida digital?",
            "hipotesis": [("violencia_digital", 0.75), ("violencia_psicologica", 0.60)]},
    "121": {"pregunta": "¿Usan tus claves para entrar a tus cuentas sin tu permiso?",
            "hipotesis": [("violencia_digital", 0.90)]},
    "122": {"pregunta": "¿Difunden rumores o mensajes falsos sobre ti por internet?",
            "hipotesis": [("violencia_digital", 0.95), ("violencia_psicologica", 0.80)]},
    "123": {"pregunta": "¿Te etiquetan o mencionan en publicaciones sin tu autorización?",
            "hipotesis": [("violencia_digital", 0.65)]},
    "124": {"pregunta": "¿Te exigen enviar tu ubicación cada vez que sales?",
            "hipotesis": [("violencia_digital", 0.80), ("violencia_psicologica", 0.70)]},
    "125": {"pregunta": "¿Borran contactos, chats o historial para aislarte o controlarte?",
            "hipotesis": [("violencia_digital", 0.90), ("violencia_psicologica", 0.85)]},
    "126": {"pregunta": "¿Recibes mensajes repetidos para presionarte, vigilarte o molestarte?",
            "hipotesis": [("violencia_digital", 0.85), ("violencia_psicologica", 0.70)]},

    # DIMENSIÓN: NEGLIGENCIA (127-147)
    "127": {"pregunta": "¿Te dejan sin comida suficiente o sin acceso regular a alimentos?",
            "hipotesis": [("negligencia", 0.95), ("violencia_fisica", 0.60)]},
    "128": {"pregunta": "¿No te atienden cuando estás enfermo/a o con dolor?",
            "hipotesis": [("negligencia", 0.90), ("violencia_fisica", 0.40)]},
    "129": {"pregunta": "¿Te dejan solo/a sin la supervisión necesaria?", "hipotesis": [("negligencia", 0.85)]},
    "130": {"pregunta": "¿Olvidan o dejan de darte medicamentos que necesitas?",
            "hipotesis": [("negligencia", 0.95), ("violencia_fisica", 0.50)]},
    "131": {"pregunta": "¿No te llevan a consultas o revisiones médicas importantes?",
            "hipotesis": [("negligencia", 0.85)]},
    "132": {"pregunta": "¿Te dejan sin ropa, abrigo o artículos básicos necesarios?",
            "hipotesis": [("negligencia", 0.90)]},
    "133": {"pregunta": "¿No cubren necesidades básicas de higiene de forma repetida?",
            "hipotesis": [("negligencia", 0.90)]},
    "134": {"pregunta": "¿No responden a emergencias cuando necesitas ayuda?", "hipotesis": [("negligencia", 0.95)]},
    "135": {"pregunta": "¿Te dejan en un lugar inseguro o riesgoso sin cuidado?",
            "hipotesis": [("negligencia", 0.90), ("violencia_fisica", 0.40)]},
    "136": {"pregunta": "¿No respetan o no permiten un descanso adecuado cuando lo necesitas?",
            "hipotesis": [("negligencia", 0.75), ("violencia_fisica", 0.50)]},
    "137": {"pregunta": "¿Te niegan apoyo básico para cubrir necesidades esenciales?",
            "hipotesis": [("negligencia", 0.90), ("violencia_economica", 0.60)]},
    "138": {"pregunta": "¿Te dejan esperando de manera constante sin recogerte o acompañarte cuando hace falta?",
            "hipotesis": [("negligencia", 0.80), ("violencia_psicologica", 0.40)]},
    "139": {"pregunta": "¿Vives o pasas tiempo en condiciones insalubres que no corrigen?",
            "hipotesis": [("negligencia", 0.90)]},
    "140": {"pregunta": "¿No te protegen cuando otra persona te agrede o te pone en riesgo?",
            "hipotesis": [("negligencia", 0.95), ("violencia_psicologica", 0.60)]},
    "141": {"pregunta": "¿Ignoran señales claras de malestar, dolor o cansancio?",
            "hipotesis": [("negligencia", 0.85)]},
    "142": {"pregunta": "¿No te dan transporte o apoyo para asistir a citas importantes?",
            "hipotesis": [("negligencia", 0.80)]},
    "143": {"pregunta": "¿Dejan a menores sin la supervisión necesaria por periodos inadecuados?",
            "hipotesis": [("negligencia", 0.95)]},
    "144": {"pregunta": "¿Te dejan sin acceso regular a agua o servicios básicos?",
            "hipotesis": [("negligencia", 0.95), ("violencia_fisica", 0.50)]},
    "145": {"pregunta": "¿No corrigen riesgos domésticos obvios y peligrosos?", "hipotesis": [("negligencia", 0.85)]},
    "146": {"pregunta": "¿Te cargan responsabilidades de cuidado para las que no tienes capacidad o apoyo?",
            "hipotesis": [("negligencia", 0.75), ("violencia_psicologica", 0.60)]},
    "147": {"pregunta": "¿Te ignoran por completo cuando estás en crisis o muy mal?",
            "hipotesis": [("negligencia", 0.90), ("violencia_psicologica", 0.70)]},

    # DIMENSIÓN: COMPORTAMIENTOS MIXTOS DE ALTO RIESGO (148-150)
    "148": {"pregunta": "¿Te impiden salir de casa y además revisan tu celular para controlarte?",
            "hipotesis": [("violencia_psicologica", 0.90), ("violencia_digital", 0.85), ("violencia_fisica", 0.60)]},
    "149": {"pregunta": "¿Te controlan el dinero y te insultan cuando pides algo básico?",
            "hipotesis": [("violencia_economica", 0.90), ("violencia_verbal", 0.85), ("violencia_psicologica", 0.70)]},
    "150": {"pregunta": "¿Después de una agresión no te llevan a revisión médica ni te apoyan?",
            "hipotesis": [("negligencia", 0.95), ("violencia_fisica", 0.80), ("violencia_psicologica", 0.85)]},
}
